name: Dummy CI Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"

